### ISSUE TITLE
Onboard to conda-forge

### ISSUE THREAD

**Issue by ngoldbaum** [Point72/csp#10]
Right now csp bootstraps the majority of build dependencies using `vcpkg`. However, if we want to eventually add a build of csp to conda-forge we will need to define a conda recipe that gets its build dependencies from conda-forge instead.

From `vcpkg.json` we have:

```
{
    "name": "main",
    "version-string": "latest",
    "dependencies": [
      "abseil",
      "arrow",
      "brotli",
      "exprtk",
      "gtest",
      "librdkafka",
      "lz4",
      "parquet",
      "protobuf",
      "rapidjson",
      "thrift",
      "utf8proc"
    ],
    "overrides": [
      { "name": "arrow", "version": "7.0.0"}
    ],
    "builtin-baseline": "288e8bebf4ca67c1f8ebd49366b03650cfd9eb7d"
  }
```

This corresponds to the following `conda-forge` dependencies:

```
abseil-cpp
arrow-cpp 7.0.0
brotli
exprtk
gtest
librdkafka
lz4
libparquet
protobuf
rapidjson
thrift
utf8proc
```

The main problem I can see in this dependency list is the pin on `arrow-cpp` 7.0.0. It looks conda-forge [hasn't updated this version in 1 year 8 months](https://anaconda.org/conda-forge/arrow-cpp/files?page=5&version=7.0.0). Version 7.0.1 was updated a little more recently, [a year ago](https://anaconda.org/conda-forge/arrow-cpp/files?page=5&version=7.0.1).

Looking at older `arrow-cpp` packages on conda-forge, since they depend on Python, the pin would also restrict us from supporting newer python versions, since python 3.11 and 2.12 don't have arrow-cpp 7.0.0 packages available. It looks like `arrow-cpp` dropped its python dependency starting with `arrow-cpp 10`.

I don't have context for why the pin on arrow is set the way it is. Can it be loosened at all?

**Comment by ngoldbaum** [comment]
@timkpaine reading over your conda recipe above - how is it able to build csp without g++ on a mac? Or did you never try doing that?

**Comment by timkpaine** [comment]
note that after https://github.com/Point72/csp/pull/22, we will need 

```yaml
run_constrained:
    - slack-sdk >=3
```

ref: https://github.com/Point72/csp/issues/35

**Comment by isuruf** [comment]
Micromamba is the only package that I know that does vcpkg and that's only because of windows and issues with building static libraries across visual studio versions.

I'm not convinced that using vcpkg and static libraries is better here.

**Comment by timkpaine** [comment]
@isuruf many bazel-based projects bring in external deps themselves, as do e.g. every single rust/python package. I don't think argument is that its preferable (as it makes for longer builds) but it is a lot of separate CMake code to maintain for little to no runtime benefit. Any dep that works with a simple `find_package(< > CONFIG)` will likely need its own individual `find_package` script, which will be brittle (they always are).

**Comment by isuruf** [comment]
Yes, bazel projects and rust projects bring in lots of external deps themselves and we have lots of issues with bazel projects due to that. (rust projects less so because they mostly use rust external deps)

The issue with vendoring is that a project has to maintain the dependencies themselves. When there are updates/bug-fixes/security-fixes to dependencies, the package needs to be rebuilt instead of just updating the dependencies. This means that only the recent versions get these updates/bug-fixes/security-fixes. It also results in larger packages and also takes longer.

**Comment by timkpaine** [comment]
@isuruf yep of course, i think the tradeoff is on maintenance of 2 sets of dependency management scripts (e.g. 1 for vcpkg toolchain necessary on certain platforms, e.g. windows and mac if cross compiling, and 1 for "external deps" including conda) vs being up-to-date on deps (e.g. we link against openssl and 3 had vulnerabilities recently). For active projects, dealing with shifting dependencies and non-normalized deps where you need to write and maintain many of your own FindPackage.cmake files, the former is worse than the latter. From a conda-forge perspective, we'll have longer build times but we shouldn't have the incompatibiltiies of e.g. bazel packages due to the linkage mechanism. Also our build time is much shorter than many other packages I maintain, so I wouldn't think that would be a barrier to onboarding.
