### ISSUE TITLE
Support `csp` on Windows

### ISSUE THREAD

**Issue by robambalu** [Point72/csp#109]
@ngoldbaum if you can create a branch that setups up a build env on windows, I can work on getting the windows build working

**Comment by ngoldbaum** [comment]
I've gotten to the point of building csp itself on a windows box, but the build fails trying to find `brotli`:

```
CMake Error at cpp/cmake/modules/FindBrotli.cmake:92 (message):
--
Could not find the Brotli library.  Looked in in
C:/Users/goldbaum/csp/_skbuild/win-amd64-3.11/cmake-build/vcpkg_installed/x64-windows.
Call Stack (most recent call first):
vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
cpp/cmake/modules/FindDepsParquetAdapter.cmake:13 (find_package)
vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
CMakeLists.txt:304 (find_package)
 
 
-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
File "C:\Users\goldbaum\mambaforge\envs\csp\Lib\site-packages\skbuild\setuptools_wrap.py", line 666, in setup
env = cmkr.configure(
^^^^^^^^^^^^^^^
File "C:\Users\goldbaum\mambaforge\envs\csp\Lib\site-packages\skbuild\cmaker.py", line 357, in configure
raise SKBuildError(msg)
 
An error occurred while configuring with CMake.
```

Looking at [the contents of `FindBrotli.cmake`](https://github.com/Point72/csp/blob/main/cpp/cmake/modules/FindBrotli.cmake) it seems to be specifically looking for unix static libraries with a `.a` suffix. I think we just need to add some more names that might appear on windows too. [The version of this in apache `parquet-cpp`](https://github.com/apache/parquet-cpp/blob/master/cmake_modules/FindBrotli.cmake) might work on windows too?

**Comment by robambalu** [comment]
Do you have the steps you took to get to this point?

**Comment by ngoldbaum** [comment]
See #123

**Comment by robambalu** [comment]
Sorry I'm still getting used to github.  How do I checkout your forked clone / branch, do I need a fresh git clone or can I do it in an existing area?

**Comment by ngoldbaum** [comment]
Do the instructions from the dev guide in #117 help?

https://github.com/Point72/csp/blob/7f24717460753a36f2bdb2b806d961c5f23f12e6/docs/DEVELOPER_GUIDE.md#how-to-check-out-a-pr-locally

Although I see now the second-to-last step has a typo, it should be `git switch`.

Those instructions are nice because you don’t need any info about forks to follow them, but if I’m working with someone a lot I’ll often add their fork as a remote for my clone and pull from the contributor’s fork directly without using the github-specific PR ref trick described there.

You can configure my fork of `csp` as a git remote on your clone and pull the PR branch from my fork:

```
$ git remote add ngoldbaum https://github.com/ngoldbaum/csp
$ git fetch ngoldbaum windows-dev-enc
$ git checkout windows-dev-env
```

(you can read my branch name in the header of the PR description)
