### ISSUE TITLE
manylinux wheel building with old GCC string ABI

### ISSUE THREAD

**Issue by robambalu** [Point72/csp#114]
We have a requirement to build against csp libraries for extended C++ adapters using the newer string ABI.
As it stands now, the manylinux wheel is being built with the old CXX string ABI and therefore wont be compatible with existing builds.

Sample issue being hit, from autogenerated code:
```
In file included from /home/ra7293/user/hfalgo_csp_trading/_skbuild/linux-x86_64-3.11/cmake-build/cpp/csp-trading/adapters/onefeed/csp_autogen/onefeed_types.cpp:2:
/home/ra7293/user/hfalgo_csp_trading/_skbuild/linux-x86_64-3.11/cmake-build/cpp/csp-trading/adapters/onefeed/csp_autogen/onefeed_types.h: In member function 'const std::string& csp::autogen::Header::session_id() const':
/home/ra7293/user/hfalgo_csp_trading/_skbuild/linux-x86_64-3.11/cmake-build/cpp/csp-trading/adapters/onefeed/csp_autogen/onefeed_types.h:455:46: error: static assertion failed
  455 |         static_assert( sizeof( std::string ) == 8 );
```

code was generated using the csp wheel's libraries, which have std::string as 8 bytes ( old ABI )
but the compilation we're doing is the new ABI, and so this assertion fails

**Comment by ngoldbaum** [comment]
@robambalu I tried working around this using a newer manylinux build image, but in the end that won't work because of the requirement that the wheels are runnable on RHEL 7/CentOS 7, which has glibc 2.17, and the newest manylinux package that supports such an old glibc is manylinux 2014.

So we're at an impasse, because according to the discussion in [this discourse thread](https://discuss.python.org/t/how-to-set-glibcxx-use-cxx11-abi-for-manylinux2014-and-manylinux2010-wheels/10551) and this [red hat bug tracker entry](https://bugzilla.redhat.com/show_bug.cgi?id=1546704), it's not possible to build binaries exporting the new gcc ABI in the manylinux2014 image. It looks like [pytorch is dealing with a similar issue](https://github.com/pytorch/pytorch/issues/51039).

I'm curious how you're working around this limitation for your internal builds. Are you using your own build of gcc and libstdc++? If so, maybe you need to be builing wheels internally as well?

**Comment by robambalu** [comment]
I see, thanks Nathan.  I think it may be possible for us to update our in house build that builds against csp c++ to build that specific library with the old abi.
I’ll have to give it a shot
