### ISSUE TITLE
Event for node removed/stopped (because graph was stopped)

### ISSUE THREAD

**Issue by Roh-codeur** [Point72/csp#282]
Hi

**Is your feature request related to a problem? Please describe.**
this is more of a query really. I have a scenario where I need to know if:
1. When a sub-graph in a dynamic graph stops
2. When a node in any graph stops (because the graph stopped). 

**Describe the solution you'd like**
it seems like there is a csp.stop() which I will try for (1). Not sure if there is a method for (2). 

**Describe alternatives you've considered**
Just use the csp.stop

**Comment by robambalu** [comment]
For 1) I dont think there is any way to know this at the moment.  The common case is for dynamics to be created/destroyed by an external trigger, so that trigger could also be used to know when the dynamic stops.  In the rare case that you call csp.stop_engine( dynamic = True ) within your dynamic graph, it doesnt seem there is a currently a way to know this outside of the dynamic graph.  ( I also noticed you use the term "sub-graph", which shouldnt be confused with dynamic graph: [csp.dynamic](https://github.com/Point72/csp/wiki/csp.dynamic-API)
For 2) Use with csp.stop() within a node: [csp.stop](https://github.com/Point72/csp/wiki/CSP-Node#anatomy-of-a-cspnode)
